<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Entity\Variacion;
use Doctrine\ORM\Query;

/**
 * VariacionRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class VariacionRepository extends EntityRepository
{

    /**
    * @return Array
    */
    public function findUltimaVariacion ( $criteria )
    {
	$claveVivienda = $criteria['claveVivienda'];
	$qb = $this->createQueryBuilder('v')
		->select('v')
		->andWhere('v.claveVivienda = :claveVivienda')
		->andWhere('v.tipoVariacion <> :tipoVariacion')
		->orderBy('v.fechaVariacion','DESC');
	
        $qb->setParameter( 'claveVivienda', $claveVivienda );
	$qb->setParameter( 'tipoVariacion', 'BM' );
        $result = $qb->getQuery()->getResult();
//	dump($result[0]);die;
	return $result[0];
    }
}
