# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
    erase_credentials: false

    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt
        AppBundle\Entity\User: plaintext

    role_hierarchy:
        ROLE_API:         ROLE_API
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_API, ROLE_USER, ROLE_ADMIN]

    providers:
        chain_provider:
            chain:
               providers: [fos_userbundle, fr3d_ldapbundle]
        fr3d_ldapbundle:
            id: fr3d_ldap.security.user.provider
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        main:
            pattern: ^/
            http_basic:   true
            fr3d_ldap_httpbasic: ~
            fr3d_ldap:  ~
            form_login:
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager

            logout:       true
            anonymous:    true

    access_control:
        - { path: ^/errolda-txartela, role: ROLE_API }
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_ADMIN }